import 'server-only';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// Single shared helper used by every Sprint 3 feature ('download as PDF'
// requirement). Produces a polished, PrepX-branded PDF from a generic
// section list. Each feature owns its mapping from feature-rows → sections.
//
// Returns a Uint8Array suitable for `new NextResponse(buffer, …)`.

export interface PdfSection {
  heading: string;             // 18pt bold
  body: string;                // wrapped paragraph (\n\n separates paragraphs)
  bullets?: string[];          // each rendered as "• item"
  callout?: string;            // boxed quote (e.g. mnemonic text)
}

export interface PdfTopicExportInput {
  title: string;               // page-1 hero — e.g. "Mnemonic: Fundamental Rights"
  subtitle?: string;           // tenant tag, date, etc.
  sections: PdfSection[];
  footer?: string;             // e.g. "PrepX • Generated by Hermes • 2026-05-02"
}

const PAGE_W = 595.28;          // A4 portrait, points
const PAGE_H = 841.89;
const MARGIN = 56;
const COLOR_INK     = rgb(0.07, 0.10, 0.16);  // slate-950
const COLOR_DIMMED  = rgb(0.40, 0.45, 0.55);  // slate-500
const COLOR_PRIMARY = rgb(0.13, 0.71, 0.55);  // emerald-500
const COLOR_CALLOUT = rgb(0.95, 0.97, 0.98);  // slate-50

function wrap(text: string, font: any, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const para of text.split(/\n\s*\n/)) {
    const words = para.replace(/\s+/g, ' ').trim().split(' ');
    if (words.length === 0) continue;
    let current = '';
    for (const word of words) {
      const candidate = current ? current + ' ' + word : word;
      const w = font.widthOfTextAtSize(candidate, size);
      if (w > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = candidate;
      }
    }
    if (current) lines.push(current);
    lines.push('');             // blank line between paragraphs
  }
  if (lines.length && lines[lines.length - 1] === '') lines.pop();
  return lines;
}

export async function buildTopicPdf(input: PdfTopicExportInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font     = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;
  const maxWidth = PAGE_W - 2 * MARGIN;

  const newPage = () => {
    page = pdf.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN;
  };

  // ── Title block ───────────────────────────────────────────────────
  const titleSize = 24;
  const titleLines = wrap(input.title, fontBold, titleSize, maxWidth);
  for (const line of titleLines) {
    page.drawText(line, { x: MARGIN, y: y - titleSize, size: titleSize, font: fontBold, color: COLOR_PRIMARY });
    y -= titleSize + 6;
  }
  if (input.subtitle) {
    y -= 2;
    page.drawText(input.subtitle, { x: MARGIN, y: y - 11, size: 11, font, color: COLOR_DIMMED });
    y -= 18;
  }
  // hairline
  page.drawLine({
    start: { x: MARGIN, y: y - 4 },
    end:   { x: PAGE_W - MARGIN, y: y - 4 },
    thickness: 0.5,
    color: COLOR_DIMMED,
  });
  y -= 24;

  // ── Sections ──────────────────────────────────────────────────────
  for (const section of input.sections) {
    if (y < MARGIN + 80) newPage();

    // Heading
    const headSize = 14;
    page.drawText(section.heading, { x: MARGIN, y: y - headSize, size: headSize, font: fontBold, color: COLOR_INK });
    y -= headSize + 10;

    // Body
    if (section.body) {
      const bodyLines = wrap(section.body, font, 11, maxWidth);
      for (const line of bodyLines) {
        if (y < MARGIN + 30) newPage();
        page.drawText(line, { x: MARGIN, y: y - 11, size: 11, font, color: COLOR_INK });
        y -= 14;
      }
      y -= 4;
    }

    // Callout (boxed)
    if (section.callout) {
      const calloutLines = wrap(section.callout, fontBold, 12, maxWidth - 24);
      const boxH = calloutLines.length * 16 + 18;
      if (y - boxH < MARGIN) newPage();
      page.drawRectangle({
        x: MARGIN, y: y - boxH, width: maxWidth, height: boxH,
        color: COLOR_CALLOUT,
        borderColor: COLOR_PRIMARY,
        borderWidth: 1.2,
      });
      let cy = y - 14;
      for (const line of calloutLines) {
        page.drawText(line, { x: MARGIN + 12, y: cy - 12, size: 12, font: fontBold, color: COLOR_INK });
        cy -= 16;
      }
      y -= boxH + 12;
    }

    // Bullets
    if (section.bullets && section.bullets.length) {
      for (const bullet of section.bullets) {
        const lines = wrap('• ' + bullet, font, 11, maxWidth - 12);
        for (const line of lines) {
          if (y < MARGIN + 30) newPage();
          page.drawText(line, { x: MARGIN + 4, y: y - 11, size: 11, font, color: COLOR_INK });
          y -= 14;
        }
        y -= 2;
      }
      y -= 4;
    }

    y -= 10;
  }

  // ── Footer on every page ──────────────────────────────────────────
  if (input.footer) {
    const pages = pdf.getPages();
    for (const p of pages) {
      p.drawText(input.footer, {
        x: MARGIN, y: 24,
        size: 9, font, color: COLOR_DIMMED,
      });
    }
  }

  return await pdf.save();
}

// Convenience wrapper for routes that need to return the PDF directly.
export function pdfFilename(title: string): string {
  const safe = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
  return `${safe || 'prepx'}-${new Date().toISOString().slice(0, 10)}.pdf`;
}
