import 'server-only';
import { aiChat } from '../ai-router';
import { fleschKincaidGrade } from '../text/readability';
import type { RefineArtifactType } from '../queue/types';

// Content Verifier (Sprint 2, Epic 3.2). Deeper second-pass quality gate.
//
// Runs AFTER an artifact is generated by its primary agent (script-writer,
// chapter-writer, research crawler, quiz generator). Combines local mechanical
// checks (F-K grade, citation count, distinct sources) with an LLM critique
// (factual plausibility, syllabus alignment, tone, citation discipline) into
// a single QualityReport that the admin reviews before publication.

export interface QualityFlag {
  code: string;
  severity: 'low' | 'med' | 'high';
  message: string;
  location?: string;
}

export interface QualityReport {
  status: 'passed' | 'flagged' | 'rejected';
  quality_score: number;
  readability_grade: number | null;
  citation_count: number;
  citation_urls: string[];
  syllabus_alignment_score: number;
  flags: QualityFlag[];
  remediations: string[];
  raw_report: Record<string, any>;
}

export interface VerifyArtifactInput {
  artifactType: RefineArtifactType;
  artifact: Record<string, any>;
}

// PrepX 20 UPSC subjects (lib/agents/subjects.ts mirrors these). Used so the
// LLM can ground its syllabus-alignment check.
const PREPX_SUBJECTS = [
  'Polity', 'Economy', 'Geography', 'History', 'Art & Culture', 'Environment',
  'Science & Technology', 'International Relations', 'Internal Security',
  'Ethics', 'Essay', 'Society', 'Disaster Management', 'Governance',
  'Indian Constitution', 'Modern History', 'Ancient & Medieval History',
  'Current Affairs', 'Public Administration', 'Optional Subjects',
];

const VERIFIER_SYSTEM = `You are PrepX's content verifier — a second-pass quality reviewer for UPSC exam prep artifacts.
You receive ONE artifact (a lecture script, smart-book chapter, research article, or quiz question) and produce a structured critique.

Assessment dimensions:
1. Factual plausibility — flag UPSC misconceptions you spot at a shallow read (wrong dates, wrong articles, swapped institutions, miscredited reforms). Do NOT verify obscure facts; flag only what is clearly wrong or known-misleading.
2. Syllabus alignment — does the content map to one of the 20 PrepX UPSC subjects? Score 0-100. Off-topic / generic / too-broad → low score.
3. Tone — UPSC-appropriate (formal, exam-grade, cite-and-explain). Flag casualisms, marketing fluff, hype, motivational filler, or chatbot-style hedging ("As an AI...").
4. Inline-citation discipline — are claims attributed? For chapters, are [Source: NAME] tags present in body? Are citation URLs present (when applicable)?

Output STRICT JSON only. No markdown, no fences. Schema:
{
  "syllabus_alignment_score": <0-100 integer>,
  "factual_concerns": [{"message": "string", "severity": "low|med|high"}],
  "tone_concerns":    [{"message": "string", "severity": "low|med|high"}],
  "citation_concerns":[{"message": "string", "severity": "low|med|high"}],
  "coverage_summary": "string (1-3 sentences explaining what the artifact covers and how well)"
}

Be terse. Empty arrays are valid. Do not invent flags to fill space.`;

interface VerifierLlmReport {
  syllabus_alignment_score: number;
  factual_concerns: { message: string; severity: 'low' | 'med' | 'high' }[];
  tone_concerns:    { message: string; severity: 'low' | 'med' | 'high' }[];
  citation_concerns:{ message: string; severity: 'low' | 'med' | 'high' }[];
  coverage_summary: string;
}

function parseLooseJson(raw: string): any {
  try { return JSON.parse(raw); } catch {
    const stripped = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim();
    return JSON.parse(stripped);
  }
}

function clampScore(n: any, lo: number, hi: number, fallback: number): number {
  const v = Number(n);
  if (!Number.isFinite(v)) return fallback;
  return Math.max(lo, Math.min(hi, v));
}

function normaliseSeverity(s: any): 'low' | 'med' | 'high' {
  const v = String(s || '').toLowerCase();
  if (v === 'high') return 'high';
  if (v === 'med' || v === 'medium') return 'med';
  return 'low';
}

function normaliseLlmReport(parsed: any): VerifierLlmReport {
  const mapConcerns = (arr: any): { message: string; severity: 'low' | 'med' | 'high' }[] =>
    Array.isArray(arr)
      ? arr.map((c: any) => ({
          message: String(c?.message ?? '').trim(),
          severity: normaliseSeverity(c?.severity),
        })).filter((c) => c.message.length > 0)
      : [];

  return {
    syllabus_alignment_score: clampScore(parsed?.syllabus_alignment_score, 0, 100, 50),
    factual_concerns:  mapConcerns(parsed?.factual_concerns),
    tone_concerns:     mapConcerns(parsed?.tone_concerns),
    citation_concerns: mapConcerns(parsed?.citation_concerns),
    coverage_summary:  String(parsed?.coverage_summary ?? '').trim(),
  };
}

// Extract a verifier-friendly payload depending on artifact shape.
interface ArtifactProjection {
  title: string;
  body: string;            // primary text used for F-K + LLM
  citationUrls: string[];
  citationCount: number;
  distinctSources: number;
  precomputedFK: number | null;
}

function projectArtifact(artifactType: RefineArtifactType, a: Record<string, any>): ArtifactProjection {
  switch (artifactType) {
    case 'lecture_script': {
      const cites = Array.isArray(a.source_citations) ? a.source_citations : [];
      const urls = cites.map((c: any) => String(c?.url || '')).filter(Boolean);
      return {
        title: String(a.title || ''),
        body: String(a.script_text || ''),
        citationUrls: urls,
        citationCount: cites.length,
        distinctSources: new Set(cites.map((c: any) => String(c?.title || c?.source || '').toLowerCase()).filter(Boolean)).size,
        precomputedFK: typeof a.flesch_kincaid_grade === 'number' ? a.flesch_kincaid_grade : null,
      };
    }
    case 'smart_book_chapter': {
      const cites = Array.isArray(a.source_citations) ? a.source_citations : [];
      const urls = cites.map((c: any) => String(c?.url || '')).filter(Boolean);
      const body = [a.introduction, a.detailed_content, a.summary].filter(Boolean).join('\n\n');
      return {
        title: String(a.title || ''),
        body,
        citationUrls: urls,
        citationCount: cites.length,
        distinctSources: new Set(cites.map((c: any) => String(c?.source || '').toLowerCase()).filter(Boolean)).size,
        precomputedFK: typeof a.flesch_kincaid_grade === 'number' ? a.flesch_kincaid_grade : null,
      };
    }
    case 'research_article': {
      const url = a.source_url ? [String(a.source_url)] : [];
      const body = String(a.summary || a.body_text || a.content || '');
      return {
        title: String(a.title || ''),
        body,
        citationUrls: url,
        citationCount: url.length,
        distinctSources: url.length > 0 ? 1 : 0,
        precomputedFK: null,
      };
    }
    case 'quiz_question': {
      // Quiz questions live inside `quizzes.questions` JSONB (no dedicated
      // table). The caller must supply the single-question shape.
      const stem = String(a.question || a.stem || '');
      const explanation = String(a.explanation || '');
      const body = `${stem}\n\n${explanation}`;
      const url = a.source_url ? [String(a.source_url)] : [];
      return {
        title: stem.slice(0, 80),
        body,
        citationUrls: url,
        citationCount: url.length,
        distinctSources: url.length > 0 ? 1 : 0,
        precomputedFK: null,
      };
    }
  }
}

// Local mechanical checks → flags. Severity is set conservatively so the
// LLM critique can promote to 'rejected' via 'high' severity.
function mechanicalFlags(p: ArtifactProjection, fk: number | null, artifactType: RefineArtifactType): { flags: QualityFlag[]; remediations: string[] } {
  const flags: QualityFlag[] = [];
  const rems: string[] = [];

  // Readability
  if (fk === null) {
    flags.push({ code: 'FK_NULL', severity: 'med', message: 'Body too short to compute Flesch-Kincaid grade.' });
    rems.push('Expand the body so a reading-grade metric can be computed (≥3 sentences).');
  } else if (artifactType === 'smart_book_chapter' && fk > 11) {
    flags.push({ code: 'FK_HIGH', severity: 'med', message: `F-K grade ${fk} exceeds chapter ceiling of 11.` });
    rems.push('Shorten sentences and replace polysyllabic words with concrete nouns.');
  } else if (artifactType === 'lecture_script' && fk > 12) {
    flags.push({ code: 'FK_HIGH', severity: 'med', message: `F-K grade ${fk} exceeds script ceiling of 12.` });
    rems.push('Shorten sentences. Lectures should sit at grade 9-11 for spoken delivery.');
  }

  // Citations — only enforced for chapters & scripts (research articles already
  // ship their source URL; quiz questions sometimes do not need a citation).
  if (artifactType === 'smart_book_chapter' || artifactType === 'lecture_script') {
    if (p.citationCount < 3) {
      flags.push({ code: 'CITATIONS_LOW', severity: 'high', message: `Only ${p.citationCount} citations (minimum 3).` });
      rems.push('Add at least 3 citations from canonical UPSC sources (NCERT, Laxmikanth, PIB, Yojana, IGNOU, ARC).');
    }
    if (p.distinctSources < 2) {
      flags.push({ code: 'SOURCES_LOW', severity: 'med', message: `Only ${p.distinctSources} distinct sources (minimum 2).` });
      rems.push('Diversify sources: cite at least 2 different canonical works.');
    }
  } else if (artifactType === 'research_article' && p.citationCount === 0) {
    flags.push({ code: 'NO_SOURCE_URL', severity: 'high', message: 'Research article has no source_url.' });
    rems.push('Re-crawl the article so its source URL is recorded.');
  }

  return { flags, remediations: rems };
}

function llmFlags(report: VerifierLlmReport): { flags: QualityFlag[]; remediations: string[] } {
  const flags: QualityFlag[] = [];
  const rems: string[] = [];

  for (const c of report.factual_concerns) {
    flags.push({ code: 'FACTUAL', severity: c.severity, message: c.message });
  }
  for (const c of report.tone_concerns) {
    flags.push({ code: 'TONE', severity: c.severity, message: c.message });
  }
  for (const c of report.citation_concerns) {
    flags.push({ code: 'CITATION', severity: c.severity, message: c.message });
  }

  if (report.syllabus_alignment_score < 60) {
    flags.push({
      code: 'SYLLABUS_OFF',
      severity: report.syllabus_alignment_score < 40 ? 'high' : 'med',
      message: `Syllabus alignment score ${report.syllabus_alignment_score}/100.`,
    });
    rems.push(`Re-anchor the artifact to one of the PrepX UPSC subjects: ${PREPX_SUBJECTS.slice(0, 8).join(', ')}, …`);
  }

  if (report.factual_concerns.some((c) => c.severity === 'high')) {
    rems.push('Cross-check flagged facts against NCERT / Laxmikanth before publishing.');
  }
  if (report.tone_concerns.length > 0) {
    rems.push('Rewrite tone to formal exam-grade (no hype, no chatbot hedging, no marketing copy).');
  }

  return { flags, remediations: rems };
}

function computeQualityScore(input: {
  fk: number | null;
  citationCount: number;
  syllabusAlignment: number;
  flags: QualityFlag[];
  artifactType: RefineArtifactType;
}): number {
  // Readability subscore (0-40). Treat 9-11 as ideal for chapters; 9-12 for
  // scripts; for articles/quiz we use 8-13 as the wider acceptance band.
  const fk = input.fk;
  let readability: number;
  if (fk === null) readability = 20; // missing → middling
  else {
    const ideal: [number, number] =
      input.artifactType === 'smart_book_chapter' ? [9, 11] :
      input.artifactType === 'lecture_script'     ? [9, 12] : [8, 13];
    if (fk >= ideal[0] && fk <= ideal[1]) readability = 40;
    else {
      const dist = fk < ideal[0] ? ideal[0] - fk : fk - ideal[1];
      readability = Math.max(0, 40 - dist * 5);
    }
  }

  // Citation subscore (0-30). 3+ citations → full; linearly down to 0.
  let citation: number;
  if (input.artifactType === 'smart_book_chapter' || input.artifactType === 'lecture_script') {
    citation = Math.min(30, (input.citationCount / 3) * 30);
  } else {
    citation = input.citationCount > 0 ? 30 : 10;
  }

  // Syllabus alignment subscore (0-30).
  const syllabus = (input.syllabusAlignment / 100) * 30;

  let score = readability + citation + syllabus;

  // Per-flag deductions.
  for (const f of input.flags) {
    if (f.severity === 'high') score -= 10;
    else if (f.severity === 'med') score -= 4;
    else score -= 1;
  }

  return Math.max(0, Math.min(100, Math.round(score * 10) / 10));
}

function deriveStatus(score: number, flags: QualityFlag[]): 'passed' | 'flagged' | 'rejected' {
  const hasHigh = flags.some((f) => f.severity === 'high');
  if (hasHigh) return 'rejected';
  if (score < 70) return 'rejected';
  if (score >= 85) return 'passed';
  return 'flagged';
}

export async function verifyArtifact(input: VerifyArtifactInput): Promise<QualityReport> {
  const projection = projectArtifact(input.artifactType, input.artifact);

  // Local F-K. Prefer precomputed value when generator already produced one
  // (chapters do this) so we don't disagree with the generator's metric.
  const fk = projection.precomputedFK ?? fleschKincaidGrade(projection.body);

  // LLM verifier — feed it a compact, bounded view of the artifact.
  const userPayload = [
    `Artifact type: ${input.artifactType}`,
    `Title: ${projection.title || '(untitled)'}`,
    projection.body
      ? `Body (first 6000 chars):\n${projection.body.slice(0, 6000)}`
      : 'Body: (empty)',
    `Citations supplied: ${projection.citationCount} (distinct: ${projection.distinctSources}). URLs: ${projection.citationUrls.slice(0, 6).join(' | ') || 'none'}`,
  ].join('\n\n');

  let llm: VerifierLlmReport;
  try {
    const raw = await aiChat({
      messages: [
        { role: 'system', content: VERIFIER_SYSTEM },
        { role: 'user', content: userPayload },
      ],
      temperature: 0.2,
      maxTokens: 1200,
      jsonMode: true,
    });
    llm = normaliseLlmReport(parseLooseJson(raw));
  } catch (err: any) {
    // LLM down — degrade gracefully. The mechanical gate still runs and the
    // audit is recorded; the absent LLM critique is itself a flag.
    llm = {
      syllabus_alignment_score: 50,
      factual_concerns: [],
      tone_concerns: [],
      citation_concerns: [],
      coverage_summary: `LLM verifier unavailable: ${(err?.message || String(err)).slice(0, 200)}`,
    };
  }

  const mech = mechanicalFlags(projection, fk, input.artifactType);
  const llmExtracted = llmFlags(llm);

  const flags = [...mech.flags, ...llmExtracted.flags];
  const remediations = Array.from(new Set([...mech.remediations, ...llmExtracted.remediations]));

  const score = computeQualityScore({
    fk,
    citationCount: projection.citationCount,
    syllabusAlignment: llm.syllabus_alignment_score,
    flags,
    artifactType: input.artifactType,
  });
  const status = deriveStatus(score, flags);

  return {
    status,
    quality_score: score,
    readability_grade: fk,
    citation_count: projection.citationCount,
    citation_urls: projection.citationUrls,
    syllabus_alignment_score: llm.syllabus_alignment_score,
    flags,
    remediations,
    raw_report: {
      llm,
      projection: {
        title: projection.title,
        bodyLength: projection.body.length,
        distinctSources: projection.distinctSources,
      },
    },
  };
}
