'use client';

import { motion } from 'motion/react';
import { Network, BrainCircuit, Library, Swords } from 'lucide-react';

export default function CinematicFeatures() {
  return (
    <section className="relative z-10 max-w-7xl mx-auto px-4 py-24 flex flex-col gap-32">
      <FeatureBlock
        title="Hermes 24/7"
        headline="An agent team that never sleeps."
        description="Eight specialised agents — planner, scraper, quiz-writer, mnemonic-builder, script-writer, voice, video, and tutor — coordinate every night to ship your next-day plan, drills, and topic-imagination videos."
        icon={<Network className="text-blue-400" size={32} />}
        alignment="left"
      >
        <div className="w-full aspect-[4/3] md:aspect-auto md:h-[400px] bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 relative overflow-hidden flex flex-col">
          <div className="flex justify-between items-center mb-8">
            <span className="text-white/60 font-mono text-sm tracking-widest uppercase">Agent Throughput</span>
            <div className="px-3 py-1 bg-green-500/10 text-green-400 rounded-full text-xs font-bold border border-green-500/20">
              Live
            </div>
          </div>

          <div className="flex-1 flex items-end gap-2 px-2 relative">
            {[40, 55, 45, 60, 75, 65, 80, 85, 95].map((height, i) => (
              <motion.div
                key={i}
                initial={{ height: 0 }}
                whileInView={{ height: `${height}%` }}
                viewport={{ once: true }}
                transition={{ duration: 1, delay: i * 0.1, ease: 'easeOut' }}
                className={`flex-1 rounded-t-sm ${i === 8 ? 'bg-blue-500' : 'bg-white/10'}`}
              />
            ))}
            <div className="absolute left-0 right-0 bottom-1/2 border-t border-dashed border-white/20" />
            <div className="absolute right-4 bottom-1/2 translate-y-[-50%] text-white/40 text-xs font-mono">
              Daily SLA
            </div>
          </div>
        </div>
      </FeatureBlock>

      <FeatureBlock
        title="Mentor State Machine"
        headline="The AI tutor that knows your state."
        description="Bypass dumb chatbots. Hermes tracks whether you're reading, quizzing, or idle — and injects context-aware strategy, mnemonics, and instant clarifications right into your active study pane."
        icon={<BrainCircuit className="text-orange-400" size={32} />}
        alignment="right"
      >
        <div className="w-full h-[400px] bg-gradient-to-b from-[#111] to-black border border-white/10 rounded-2xl p-6 flex flex-col gap-4 relative overflow-hidden shadow-[0_0_50px_rgba(249,115,22,0.05)]">
          <div className="absolute -top-20 -right-20 w-64 h-64 bg-orange-600/10 rounded-full blur-[80px]" />

          <div className="flex items-center gap-4 mb-4 border-b border-white/5 pb-4">
            <div className="w-10 h-10 rounded-full bg-gradient-to-br from-orange-400 to-red-600 flex items-center justify-center">
              <BrainCircuit size={20} className="text-white" />
            </div>
            <div>
              <h4 className="text-white font-semibold">Chanakya AI</h4>
              <p className="text-xs text-white/50">Strategy & Mentorship</p>
            </div>
          </div>

          <div className="flex flex-col gap-3 flex-1 justify-end">
            <ChatMessage align="right" text="I keep mixing up Fundamental Rights vs DPSP." />
            <ChatMessage
              align="left"
              text="Mnemonic — Rights Rule, Directives Drive. Rights are justiciable; Directives are aspirational. Want a 3-question drill?"
            />
            <ChatMessage align="left" text="Build me a 5-card flash drill on Article 14–18" isAction />
          </div>
        </div>
      </FeatureBlock>

      <FeatureBlock
        title="Astra-Video & Concept Shorts"
        headline="Watch concepts, don't just read them."
        description="Topic-imagination videos for any UPSC concept — from BCE & dinosaurs to monetary policy — generated by the script-writer agent + 3D scene renderer + Manim + LTX-Video. Plus 120-second concept shorts for revision."
        icon={<Library className="text-emerald-400" size={32} />}
        alignment="left"
      >
        <div className="w-full h-[400px] bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 relative overflow-hidden flex flex-col justify-between">
          <div className="flex justify-between items-center">
            <span className="text-white/60 font-mono text-sm tracking-widest uppercase">Astra Studio</span>
            <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center animate-pulse">
              <div className="w-3 h-3 bg-emerald-500 rounded-full" />
            </div>
          </div>

          <div className="flex flex-col items-center gap-6">
            <div className="w-32 h-32 rounded-full border-4 border-emerald-500/30 flex items-center justify-center relative overflow-hidden shadow-[0_0_40px_rgba(16,185,129,0.2)]">
              <div className="absolute inset-0 bg-emerald-500/10 animate-ping" />
              <VolumeBars />
            </div>
            <div className="text-center">
              <h3 className="text-white text-xl font-bold">Indus Valley — 3D walkthrough</h3>
              <p className="text-white/50 text-sm">Ancient History • 120s concept short</p>
            </div>
          </div>

          <div className="w-full h-1 bg-white/10 rounded-full overflow-hidden">
            <div className="w-1/3 h-full bg-emerald-500" />
          </div>
        </div>
      </FeatureBlock>

      <FeatureBlock
        title="Squads & Territory Conquest"
        headline="A 3D map of India you actually capture."
        description="Form squads, master topics, capture districts on the live 3D conquest map. Real-time leaderboards, persistent ownership, and a coin economy that rewards consistency over cramming."
        icon={<Swords className="text-purple-400" size={32} />}
        alignment="right"
      >
        <div className="w-full h-[400px] bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 relative overflow-hidden flex flex-col items-center justify-center">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(168,85,247,0.08),transparent_60%)]" />

          <div className="relative z-10 flex gap-8 items-center bg-black/60 backdrop-blur-md p-6 rounded-2xl border border-white/10">
            <div className="flex flex-col items-center gap-2">
              <div className="w-16 h-16 rounded-full bg-blue-500 flex items-center justify-center text-white font-bold text-xl ring-4 ring-blue-500/30">
                You
              </div>
              <span className="text-white/60 text-sm">Lv. 42</span>
            </div>

            <div className="flex flex-col items-center">
              <Swords className="text-white/30 mb-2" size={24} />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-purple-500 font-bold text-2xl tracking-widest">
                VS
              </span>
            </div>

            <div className="flex flex-col items-center gap-2">
              <div className="w-16 h-16 rounded-full bg-red-500 flex items-center justify-center text-white font-bold text-xl ring-4 ring-red-500/30">
                Alex
              </div>
              <span className="text-white/60 text-sm">Lv. 45</span>
            </div>
          </div>

          <p className="mt-8 text-white/50 font-mono text-sm uppercase tracking-widest relative z-10">
            District: New Delhi • Capture in 02:45:00
          </p>
        </div>
      </FeatureBlock>
    </section>
  );
}

function FeatureBlock({
  title,
  headline,
  description,
  icon,
  alignment,
  children,
}: {
  title: string;
  headline: string;
  description: string;
  icon: React.ReactNode;
  alignment: 'left' | 'right';
  children: React.ReactNode;
}) {
  const isLeft = alignment === 'left';

  return (
    <div className={`flex flex-col gap-12 items-center ${isLeft ? 'md:flex-row' : 'md:flex-row-reverse'}`}>
      <div className="flex-1 space-y-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          className="flex items-center gap-3"
        >
          {icon}
          <span className="text-white/60 font-mono tracking-widest uppercase text-sm">{title}</span>
        </motion.div>

        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ delay: 0.1 }}
          className="text-4xl md:text-5xl font-bold text-white tracking-tight leading-[1.1]"
        >
          {headline}
        </motion.h2>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ delay: 0.2 }}
          className="text-lg text-gray-400 font-light leading-relaxed max-w-lg"
        >
          {description}
        </motion.p>
      </div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        whileInView={{ opacity: 1, scale: 1 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.6, ease: 'easeOut' }}
        className="flex-1 w-full"
      >
        {children}
      </motion.div>
    </div>
  );
}

function ChatMessage({ align, text, isAction = false }: { align: 'left' | 'right'; text: string; isAction?: boolean }) {
  const isRight = align === 'right';
  return (
    <div className={`flex ${isRight ? 'justify-end' : 'justify-start'}`}>
      <div
        className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${
          isAction
            ? 'bg-orange-500/20 text-orange-200 border border-orange-500/30 cursor-pointer hover:bg-orange-500/30 transition-colors'
            : isRight
              ? 'bg-white/10 text-white rounded-br-sm'
              : 'bg-black/50 text-white/80 border border-white/5 rounded-bl-sm backdrop-blur-md'
        }`}
      >
        {text}
      </div>
    </div>
  );
}

function VolumeBars() {
  return (
    <div className="flex items-center gap-1">
      {[1, 2, 3, 4, 3, 2, 1].map((v, i) => (
        <motion.div
          key={i}
          className="w-1.5 bg-emerald-400 rounded-full"
          animate={{ height: [`${v * 8}px`, `${(v + 2) * 8}px`, `${v * 8}px`] }}
          transition={{ duration: 0.8, repeat: Infinity, delay: i * 0.1 }}
        />
      ))}
    </div>
  );
}
